SET SCHEMA EBILLINGDEV;

CREATE TABLE USER
( 
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 CACHE 20 )
  , USERNAME VARCHAR(50) NOT NULL WITH DEFAULT ''
  , PRIMARY KEY ( ID ) );

  CREATE TABLE RECURRING_CODE
( 
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 CACHE 20 )
  , CODE VARCHAR(50) NOT NULL WITH DEFAULT ''
  , PRIMARY KEY ( ID ) );


  CREATE VIEW "EBILLINGDEV"."V_BILL_TEMPLATE_TYPE" ("USERNAME", "RECURRING_CODE", "COUNT") AS

        SELECT 
            TMP.USERNAME
            , RECURRING_CODE
            , COUNT(*) AS COUNT
            FROM BILL_ITEM_TEMPLATE TMP
            LEFT JOIN USER 
                ON USER.USERNAME = TMP.USERNAME
            LEFT JOIN RECURRING_CODE RCOD
                ON RCOD.CODE = TMP.RECURRING_CODE
            WHERE ACTIVE = 1
            GROUP BY 
                TMP.USERNAME
                , RECURRING_CODE;

