CREATE TABLE BILL ( 
      ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 CACHE 20 )
    , DESCRIPTOR VARCHAR(50) NOT NULL WITH DEFAULT '' -- JANUARY, WEEK 2, MOND
    , CYCLE_TYPE VARCHAR(30) NOT NULL WITH DEFAULT '' -- YEARLY, MONTH, WEEK, BIWEEK, DAILY
    , YEAR INT NOT NULL WITH DEFAULT -1 
    , MONTH INT NOT NULL WITH DEFAULT -1 -- 1 FOR JAN, 2 FOR FEB
    , WEEK INT NOT NULL WITH DEFAULT -1 -- 1 FOR WEEK ONE, 2 FOR WEEK 2
    , DAY  INT NOT NULL WITH DEFAULT -1 -- 1 FOR SUN , 2 FOR MON
    , START_DATE DATE NOT NULL
    , END_DATE DATE NOT NULL
    , STATUS VARCHAR(20) NOT NULL WITH DEFAULT '' 
    , STATUS_DATE TIMESTAMP NOT NULL 
    , ACTIVE INT NOT NULL WITH DEFAULT 1
    , USERNAME VARCHAR(50) NOT NULL WITH DEFAULT ''
    , CREATED_ON TIMESTAMP NOT NULL WITH DEFAULT NULL
    , CREATED_BY VARCHAR(50) NOT NULL WITH DEFAULT ''
    , MODIFIED_ON TIMESTAMP NOT NULL WITH DEFAULT NULL
    , MODIFIED_BY VARCHAR(50) NOT NULL WITH DEFAULT ''
    , PRIMARY KEY ( ID ) );
