CREATE TABLE TRANSACTION
( 
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 CACHE 20 )
  , BILL_ID BIGINT NOT NULL
  , BILL_ITEM_ID BIGINT NOT NULL  
  , TYPE VARCHAR(20) NOT NULL WITH DEFAULT '' --PMT, ADJ, REV
  , REFERENCE_ID BIGINT NOT NULL WITH DEFAULT 0
  , AMOUNT DECIMAL(9,2) NOT NULL WITH DEFAULT 0
  , PREVIOUS_BALANCE DECIMAL(9,2) NOT NULL WITH DEFAULT 0
  , NEW_BALANCE DECIMAL(9,2) NOT NULL WITH DEFAULT 0
  , PAYMENT_METHOD VARCHAR(20) -- CC, CSH, MO, CHK
  , CONFIRMATION VARCHAR(50) NOT NULL WITH DEFAULT '' 
  , EXTRA_INFO1 VARCHAR(100) NOT NULL WITH DEFAULT '' -- CHCKNO, 
  , EXTRA_INFO2 VARCHAR(100) NOT NULL WITH DEFAULT ''
  , EXTRA_INFO3 VARCHAR(100) NOT NULL WITH DEFAULT ''
  , PAID_TO VARCHAR(150) NOT NULL WITH DEFAULT ''
  , PAID_BY VARCHAR(150) NOT NULL WITH DEFAULT ''
  , ENTITY_CODE VARCHAR(20) NOT NULL WITH DEFAULT '' 
  , ACTIVE INT NOT NULL WITH DEFAULT 1
  , STATUS VARCHAR(20) NOT NULL WITH DEFAULT '' 
  , STATUS_DATE TIMESTAMP NOT NULL 
  , REASON_CODE VARCHAR(20) NOT NULL WITH DEFAULT ''
  , TRANSACTION_DATE TIMESTAMP NOT NULL
  , CREATED_ON TIMESTAMP NOT NULL WITH DEFAULT NULL
  , CREATED_BY VARCHAR(50) NOT NULL WITH DEFAULT ''
  , MODIFIED_ON TIMESTAMP NOT NULL WITH DEFAULT NULL
  , MODIFIED_BY VARCHAR(50) NOT NULL WITH DEFAULT ''
  , NOTES VARCHAR(100) NOT NULL WITH DEFAULT ''
  ,PRIMARY KEY ( ID ) );