
CREATE TABLE BILL_ITEM
(
      ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE -9223372036854775808 MAXVALUE 9223372036854775807 CACHE 20 )
    , TEMPLATE_ID BIGINT NOT NULL
    , BILL_ID BIGINT NOT NULL  
    , TYPE_CODE VARCHAR(20) NOT NULL WITH DEFAULT ''
    , RECURRING_CODE VARCHAR(20) NOT NULL WITH DEFAULT ''
    , YEAR INT NOT NULL WITH DEFAULT -1 
    , MONTH INT NOT NULL WITH DEFAULT -1 -- 1 FOR JAN, 2 FOR FEB
    , WEEK INT NOT NULL WITH DEFAULT -1 -- 1 FOR WEEK ONE, 2 FOR WEEK 2
    , DAY  INT NOT NULL WITH DEFAULT -1 -- 1 FOR SUN , 2 FOR MON
    , NAME VARCHAR(50) NOT NULL WITH DEFAULT ''
    , DESCRIPTION VARCHAR(100) NOT NULL WITH DEFAULT ''
    , AMOUNT DECIMAL(9,2) NOT NULL WITH DEFAULT 0
    , DATE_DUE DATE NOT NULL WITH DEFAULT NULL
    , TIME_DUE TIME NOT NULL WITH DEFAULT NULL
    , PAY_TO VARCHAR(150) NOT NULL WITH DEFAULT ''
    , ENTITY_CODE VARCHAR(20) NOT NULL WITH DEFAULT ''
    , STATUS VARCHAR(20) NOT NULL WITH DEFAULT ''
    , STATUS_DATE TIMESTAMP NOT NULL WITH DEFAULT NULL
    , ACTIVE INT NOT NULL WITH DEFAULT 1
    , USERNAME VARCHAR(50) NOT NULL WITH DEFAULT ''
    , CREATED_ON TIMESTAMP NOT NULL WITH DEFAULT NULL
    , CREATED_BY VARCHAR(50) NOT NULL WITH DEFAULT ''
    , MODIFIED_ON TIMESTAMP NOT NULL WITH DEFAULT NULL
    , MODIFIED_BY VARCHAR(50) NOT NULL WITH DEFAULT ''
    , PRIMARY KEY ( ID ) );
