
/*
  Scheduled to run on a weekly basis to 
  create the user's weekly bills as
  configured in the BILL_ITEM_TEMPLATE 
  table. 

  Related: WEEKLY_TRIGGER

  ((DAY (CURRENT TIMESTAMP) - DAYOFWEEK(CURRENT TIMESTAMP) + 13) / 7) 
*/

-- UPDATE ANY BILLS THAT HAVE BEEN DIRECTLY CREATED BY THE USER BEFORE THIS JOB RUNS --

  MERGE INTO BILL
  USING (
    SELECT * FROM V_CREATED_BILL WHERE RECURRING_CODE = 'WEEK'
    ) CREATED
  ON BILL.USERNAME = CREATED.USERNAME
  WHEN MATCHED AND BILL.CYCLE_TYPE = 'WEEK' THEN
     UPDATE SET
          BILL.MODIFIED_BY = 'WEEKLY JOB'
        , BILL.MODIFIED_ON = CURRENT TIMESTAMP;


--CREATE ALL BILLS PENDING CREATION --

INSERT INTO BILL (
      CYCLE_TYPE
    , YEAR
    , MONTH
    , WEEK
    , START_DATE
    , END_DATE
    , STATUS
    , STATUS_DATE
    , USERNAME
    , CREATED_ON
    , CREATED_BY
    , MODIFIED_ON
    , MODIFIED_BY
)SELECT
          'WEEK'
         , YEAR (CURRENT TIMESTAMP)
         , MONTH (CURRENT TIMESTAMP)
         , WEEK (CURRENT TIMESTAMP)
         , DATE(CURRENT_DATE)
         , DATE(CURRENT_DATE + 6 DAYS)
         , 'OPEN'
         , CURRENT TIMESTAMP
         , USERNAME
         , CURRENT TIMESTAMP
         , 'MONTHLY JOB'
         , CURRENT TIMESTAMP
         , 'MONTHLY JOB'
         FROM  V_PENDING_BILL
         WHERE RECURRING_CODE = 'WEEK';


