
CREATE OR REPLACE VIEW V_BILL_TOTAL(
      BILL_ID
    , TOTAL_BILLED
    , TOTAL_PAID
)AS 
SELECT 
      BILL.ID AS BILL_ID
    , SUM(COALESCE(BIS.BILLED_AMOUNT, 0)) AS TOTAL_BILLED
    , SUM(COALESCE(BIS.PAID_AMOUNT, 0)) AS TOTAL_PAID
    FROM BILL
    LEFT OUTER JOIN V_BILL_ITEM_SUMMARY BIS
    ON BILL.ID = BIS.BILL_ID
    GROUP BY BILL.ID;

