
CREATE OR REPLACE VIEW V_BILL_SUMMARY(
      ID
    , DESCRIPTOR
    , CYCLE_TYPE
    , YEAR
    , MONTH
    , WEEK
    , DAY
    , TOTAL_BILLED
    , TOTAL_PAID
    , START_DATE
    , END_DATE
    , STATUS
    , STATUS_DATE
    , USERNAME
    , CREATED_ON
    , CREATED_BY
    , MODIFIED_ON
    , MODIFIED_BY
)
AS 
SELECT
      BILL_ID AS ID
    , DESCRIPTOR
    , CYCLE_TYPE
    , YEAR
    , MONTH
    , WEEK
    , DAY
    , TOTALS.TOTAL_BILLED
    , TOTALS.TOTAL_PAID
    , START_DATE
    , END_DATE
    , STATUS
    , STATUS_DATE
    , USERNAME
    , CREATED_ON
    , CREATED_BY
    , MODIFIED_ON
    , MODIFIED_BY
    FROM BILL 
    INNER JOIN V_BILL_TOTAL AS TOTALS
    ON BILL.ID = BILL_ID
    WHERE BILL.ACTIVE = 1;