
CREATE OR REPLACE VIEW "V_BILL_ITEM_SUMMARY" 
(     "ID"
    , "TEMPLATE_ID"
    , "BILL_ID"
    , "TYPE_CODE"
    , "RECURRING"
    , "RECURRING_CODE"
    , "YEAR"
    , "MONTH"
    , "WEEK"
    , "DAY"
    , "NAME"
    , "DESCRIPTION"
    , "BILLED_AMOUNT"
    , "PAID_AMOUNT"
    , "DATE_DUE"
    , "TIME_DUE"
    , "PAY_TO"
    , "ENTITY_CODE"
    , "STATUS"
    , "STATUS_DATE"
    , "ACTIVE"
    , "USERNAME"
    , "CREATED_ON"
    , "CREATED_BY"
    , "MODIFIED_ON"
    , "MODIFIED_BY") AS
SELECT 
      BI.ID
    , BI.TEMPLATE_ID
    , BI.BILL_ID
    , BI.TYPE_CODE
    , COALESCE(BITMP.RECURRING, 0) AS RECURRING
    , BI.RECURRING_CODE
    , BI.YEAR
    , BI.MONTH
    , BI.WEEK
    , BI.DAY
    , BI.NAME
    , BI.DESCRIPTION
    , BI.AMOUNT AS BILLED_AMOUNT
    , BIT.TOTAL_PAID AS PAID_AMOUNT
    , BI.DATE_DUE
    , BI.TIME_DUE
    , BI.PAY_TO
    , BI.ENTITY_CODE
    , BI.STATUS
    , BI.STATUS_DATE
    , BI.ACTIVE
    , BI.USERNAME
    , BI.CREATED_ON
    , BI.CREATED_BY
    , BI.MODIFIED_ON
    , BI.MODIFIED_BY
    FROM BILL_ITEM AS BI
    INNER JOIN V_BILL_ITEM_TOTAL AS BIT 
    ON BI.ID = BIT.ITEM_ID
    LEFT OUTER JOIN BILL_ITEM_TEMPLATE BITMP
    ON BITMP.ID = BI.TEMPLATE_ID 
    AND BITMP.ACTIVE = 1
    WHERE BI.ACTIVE = 1;

