
CREATE OR REPLACE VIEW V_CREATED_BILL (
      USERNAME
    , RECURRING_CODE
    , START_DATE
    , END_DATE
) AS
SELECT 
	  EXISTING.USERNAME
	, EXISTING.CYCLE_TYPE
    , EXISTING.START_DATE
    , EXISTING.END_DATE
FROM V_PENDING_BILL PEND
    RIGHT JOIN (
        SELECT * FROM BILL 
            WHERE YEAR  =  YEAR (CURRENT TIMESTAMP)
            AND MONTH   =  MONTH (CURRENT TIMESTAMP)
            AND START_DATE = CASE WHEN CYCLE_TYPE = 'MONTH'
                                THEN FIRST_DAY(CURRENT_DATE)
                            ELSE DATE(CURRENT_DATE) END	
            AND END_DATE   = CASE WHEN CYCLE_TYPE = 'MONTH' 
                                THEN LAST_DAY(CURRENT_DATE)
                            ELSE DATE(CURRENT_DATE + 6 DAYS)
                            END
    ) EXISTING 
ON PEND.USERNAME = EXISTING.USERNAME
	AND PEND.RECURRING_CODE = EXISTING.CYCLE_TYPE
WHERE PEND.USERNAME IS NULL
    AND EXISTING.USERNAME IS NOT NULL;


 COMMENT ON TABLE V_CREATED_BILL
     IS 'LISTS ALL USERS FOR WHICH BILLS HAVE BEEN CREATED AT THE TIME OF JOB';   
