CREATE OR REPLACE VIEW V_PENDING_BILL (
      USERNAME
    , RECURRING_CODE
) AS
SELECT 
	  TYPE.USERNAME
	, TYPE.RECURRING_CODE
FROM V_BILL_TEMPLATE_TYPE TYPE
    LEFT JOIN (
        SELECT * FROM BILL 
            WHERE YEAR  =  YEAR (CURRENT TIMESTAMP)
            AND MONTH   =  MONTH (CURRENT TIMESTAMP)
            AND START_DATE = CASE WHEN CYCLE_TYPE = 'MONTH'
                                THEN FIRST_DAY(CURRENT_DATE)
                            ELSE DATE(CURRENT_DATE) END	
            AND END_DATE   = CASE WHEN CYCLE_TYPE = 'MONTH' 
                                THEN LAST_DAY(CURRENT_DATE)
                            ELSE DATE(CURRENT_DATE + 6 DAYS)
                            END
    ) EXISTING 
ON TYPE.USERNAME = EXISTING.USERNAME
	AND TYPE.RECURRING_CODE = EXISTING.CYCLE_TYPE
WHERE TYPE.USERNAME IS NOT NULL
    AND EXISTING.USERNAME IS NULL;

 COMMENT ON TABLE V_PENDING_BILL
     IS 'LISTS ALL USERS FOR WHICH BILLS HAVE NOT YET BEEN CREATED AT TIME OF JOB';
	    